name: Selenium UI Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: --shm-size=2g

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules

      - name: Install dependencies
        run: npm install

      - name: Start Docker services
        run: |
          docker-compose up -d nginxwebsvr
          sleep 15
          docker ps

      - name: Verify web server is running
        run: |
          curl -f http://localhost:80 || { echo "Web server failed to start"; docker logs nginxwebsvr; exit 1; }

      - name: Wait for Selenium to be ready
        run: |
          for i in {1..30}; do
            curl -s http://localhost:4444/wd/hub/status && break || sleep 2
          done

      - name: Run Selenium tests
        env:
          TEST_BASE_URL: http://localhost
          SELENIUM_HOST: http://localhost:4444/wd/hub
        run: npm test

      - name: Stop Docker services
        if: always()
        run: docker-compose down